#!/bin/bash
# compute exhaustive holes of input .off meshes using medial and Voronoi
# each file.off create a file.medial.tb and a file.voronoi.tb file
usage()
{
    echo 'Usage: medialtype_count_meshes "argument(s)" [-rm]'
    echo ""
    echo "Count the size of the Delaunay/Voronoi complexe of .off 3D meshes."
    echo "Display the size of the inner medial axis, the outer medial axis and the boundary (or link) in terms of cells."
    echo ""
    echo "-h or --help Print this message"
}

if [ $# = 0 ]
then
	usage
fi

while [ "$1" != "" ]; do
    PARAM=`echo $1 | awk -F= '{print $1}'`
    VALUE=`echo $1 | awk -F= '{print $2}'`
    case $PARAM in
        -h | --help)
            usage
            exit
            ;;
    *)
	    IFS='.' read -ra split <<< "$1" #in order to split $1 in an array with delimiter '.'
	    if [ "${split[1]}" == "off" ]
	    then
            if [ -e "$1" ]
            then
                echo -e "\e[92m$1 \e[39m count:"
                ./build/main_medial_count "$1"
            else
                echo -e "\e[31m--- $1 \e[39mdoesn't seems to exist..."
            fi
	    else
		echo -e "\e[91m--- $1 \e[39mnot a .off file"
	    fi
            ;;
    esac
    shift
done
